services:
    suppl-ai:
        extends:
            file: ./Suppl-AI/docker-compose.yml
            service: suppl-ai
        env_file:
            - ./.env
        container_name: suppl-ai
        ports:
            - 3000:3000
        networks:
            - suppl-ai-shared-network

    llm-api:
        extends:
            file: ./LLM-API/docker-compose.yml
            service: llm-api
        container_name: llm-api
        env_file:
            - ./.env
        ports:
            - 8001:8001
        networks:
            - suppl-ai-shared-network

    database-api:
        extends:
            file: ./Database-API/docker-compose.yml
            service: database-api
        env_file:
            - ./.env
        environment:
            - MONGO_DB_URL=mongo-db:27017
            - LLM_API_URL=http://llm-api:8001
        container_name: database-api
        ports:
            - 8000:8000
        networks:
            - suppl-ai-shared-network

    mongo-db:
        extends:
            file: ./Database-API/docker-compose.yml
            service: mongo-db
        container_name: database-mongo
        env_file:
            - ./.env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        networks:
            - suppl-ai-shared-network

    mongo-express:
        extends:
            file: ./Database-API/docker-compose.yml
            service: mongo-express
        env_file:
            - ./.env
        container_name: database-mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_PASSWORD}
        ports:
            - 8081:8081
        networks:
            - suppl-ai-shared-network

volumes:
    chroma_db:
    mongodb_data:
    documents:
    node_modules:

networks:
    suppl-ai-shared-network:
        external: true
