name: Database API CI

on:
  push:
    branches:
      - main
    paths:
      - 'Database-API'
  pull_request:
    branches:
      - main
    paths:
      - 'Database-API'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Set up Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Build and start Docker containers using Docker Compose
      - name: Build and start Docker containers
        run: |
          cd Database-API  # Change to the directory where your Dockerfile is located
          echo "MONGODB_URL='${{ secrets.MONGODB_URL }}'" > .env  # Store your MongoDB URL in GitHub Secrets
          echo "SECRET_KEY_JWT='${{ secrets.SECRET_KEY_JWT }}'" > .env  # Store your JWT secret key in GitHub Secrets
          docker network create suppl-ai-shared-network
          docker-compose -f docker-compose.yml up -d --build
          if [ ! -d "tests" ] || [ -z "$(ls -A tests)" ]; then
            echo "No tests found. Skipping test step."
          else
            echo "Running tests..."
            # Run tests here
            docker-compose exec -T Database-API pytest  # Runs
          fi


      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_SERVER_KEY }}  # Store your private key in GitHub Secrets
      - name: Deploy to server
        run: |
          chmod +x ./deploy/deploy-database-api.sh
          ./deploy/deploy-database-api.sh

      # 7. Optionally, bring down the Docker containers after tests are complete
      - name: Stop and remove Docker containers
        run: |
          cd Database-API  # Change to the directory where your Dockerfile is located
          docker-compose down
